### ISSUE TITLE
How can I identify the LSF executor ?

### ISSUE THREAD

**Issue by Nuturetree** [epi2me-labs/wf-pore-c#28]
### Ask away!

I can submit the job to the SMP queue (LSF) using the order:
#BSUB -q smp
#BSUB -e %J.err
#BSUB -o %J.out
#BSUB -n 30
module load Singularity
nextflow run epi2me-labs/wf-pore-c -c config.txt -profile singularity --fastq pass.fq.gz --ref genome.fasta --mcool_resolutions 10000,20000,40000,60000,100000 --cutter DpnII --threads 30 --out_dir result --pairs --chromunity --paired_end --filter_pairs --paired_end_minimum_distance 100 --chromunity_merge_distance 5 --chunk_size 500000  --digest_annotate_threads 30 --ubam_map_threads 30 -resume -with-trace. 

To adjust the number of threads, modify the config.txt file:
executor {
    $local {
        cpus = 30
        memory = "8 GB"
    }
}

But I get the errs: 
ERROR ~ Error executing process > 'POREC:digest_align_annotate (84)'
Caused by:
  Process requirement exceeds available CPUs -- req: 120; avail: 30

I want to know how to designate the number of threads or submit jobs using the LSF executor ?

**Comment by cjw85** [comment]
The `digest_align_annotate` step of the workflow requires a non-trivial number of CPU threads to run:

```
params.ubam_map_threads + (3*params.digest_annotate_threads)
```

You have set these to parameters to 30, and hence the request for 120 CPUs total. You should lower the values of these parameters in order to reduce the total CPU resource required to be below 30.

We are looking at ways to make our resource allocations more intuitive.

Note, if you are using a compute scheduler already you ought to look into nextflow's integration with LSF: https://www.nextflow.io/docs/latest/executor.html#lsf

**Comment by Nuturetree** [comment]
thanks !! very!!

**Comment by ywang285** [comment]
> Note, if you are using a compute scheduler already you ought to look into nextflow's integration with LSF: https://www.nextflow.io/docs/latest/executor.html#lsf

Does this mean that if I use SLURM, then "-c config.txt" with below content will not work because it is not "local"? Then how should I modify the config file? Thank you so much in advance @cjw85!
$local {
cpus = 30
memory = "8 GB"
}
}
